export interface Product {
  productClass: string,
  productInitial: string,
  productName: string,
  licene: string,
  agent: string,
  technologyClass: string,
  technology: string,
  tickets: number,
  sales: number,
  earning: number,
}

export const TopSelling: Product[] = [

  {
    productClass: 'btn-info',
    productInitial: 'T',
    productName: 'Tienda Comas PLazavea',
    licene: '12/11/2020',
    agent: 'Pendiente',
    technologyClass: 'label-danger',
    technology: 'Angular',
    tickets: 46,
    sales: 356,
    earning: 28.0,
  },
  {
    productClass: 'btn-orange',
    productInitial: 'p',
    productName: 'Pizza Hut',
    licene: '10/11/2020',
    agent: 'Aprobado',
    technologyClass: 'label-info',
    technology: 'Vue Js',
    tickets: 46,
    sales: 356,
    earning: 35.0,
  },
  {
    productClass: 'btn-success',
    productInitial: 'R',
    productName: 'Rappi transaccion',
    licene: '07/11/2020',
    agent: 'Aprobado',
    technologyClass: 'label-success',
    technology: 'Bootstrap',
    tickets: 46,
    sales: 356,
    earning: 20.0,
  },
  {
    productClass: 'btn-purple',
    productInitial: 'I',
    productName: 'iStore',
    licene: '01/11/2020',
    agent: 'Aprobado',
    technologyClass: 'label-purple',
    technology: 'React',
    tickets: 46,
    sales: 356,
    earning: 5000.0,
  },

]
